import { toDecrypt } from "./Converter";
import { GetData } from "./UserData";

const createInitialAppDetails = (direct) => {
  const USRNAME = toDecrypt(localStorage.getItem("USRFN"));
  const ROLE = GetData('ROLE')
  const BRANCH = GetData("BRANCH");
  console.log("ROLE from localStorage:", ROLE);
  return {
    ofwcontactNo: "",
    ls_year: "",
    ls_month: "",
    dataPrivacy: 0,
    loanProd: "",
    loanRenewal: 0,
    loanDateDep: "",
    loanBranch: ROLE && ROLE.toString() === "20" ? parseInt(BRANCH) : 0,
    loanPurpose: "",
    loanAmount: "",
    loanTerms: "",
    hckfi: "",
    withConsultant: direct ? 0 : 1,
    consultName: direct ? "" : ROLE && ROLE.toString() === "20" ? USRNAME : "",
    consultNumber: "",
    consultProfile: "",
    loanReferredBy: "",
    rentAmount: 0,
    ofwfname: "",
    ofwmname: "",
    withOfwMName: 0,
    ofwlname: "",
    ofwsuffix: "",
    ofwbdate: "",
    ofwgender: "",
    ofwmstatus: "",
    ofwemail: "",
    ofwmobile: "",
    ofwfblink: "",
    ofwresidences: "",
    ofwPresProv: "",
    ofwPresMunicipality: "",
    ofwPresBarangay: "",
    ofwPresStreet: "",
    ofwSameAdd: 0,
    ofwPermProv: "",
    ofwPermMunicipality: "",
    ofwPermBarangay: "",
    ofwPermStreet: "",
    ofwdependents: "",
    ofwvalidid: "",
    ofwidnumber: "",
    ofwcountry: "",
    ofwjobtitle: "",
    ofwcompany: "",
    ofwsalary: "",
    benfname: "",
    benmname: "",
    withBenMName: 0,
    benlname: "",
    bensuffix: "",
    benbdate: "",
    bengender: "",
    benmstatus: "",
    benemail: "",
    bennumber: "",
    benrelationship: "",
    bensameadd: 0,
    benpresprov: "",
    benpresmunicipality: "",
    benpresbarangay: "",
    benpresstreet: "",
  };
};

export default createInitialAppDetails;