export const ListData = () => {
    const dataList = [
        {
            key: 'LA-OFW-63117395',
            lan: 'LA-OFW-63117395',
            loanProd: 'OFW - Loan Abroad',
            cName: 'OGRE MAGE',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'NEW',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63153680',
            lan: 'LA-OFW-63153680',
            loanProd: 'DH - Loan Abroad',
            cName: 'LUNA MOONFANG',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63135640',
            lan: 'LA-OFW-63135640',
            loanProd: 'OFW - Loan Abroad',
            cName: 'CRYSTAL MAIDEN',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63123177',
            lan: 'LA-OFW-63123177',
            loanProd: 'OFW - Loan Abroad',
            cName: 'MEEPOO',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63124531',
            lan: 'LA-OFW-63124531',
            loanProd: 'OFW - Loan Abroad',
            cName: 'RUBIC',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63128222',
            lan: 'LA-OFW-63128222',
            loanProd: 'OFW - Loan Abroad',
            cName: 'SLARK',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63148968',
            lan: 'LA-OFW-63148968',
            loanProd: 'OFW - Loan Abroad',
            cName: 'INVOKER',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'NEW',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63520968',
            lan: 'LA-OFW-63520968',
            loanProd: 'OFW - Loan Abroad',
            cName: 'URSA',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63562008',
            lan: 'LA-OFW-63562008',
            loanProd: 'OFW - Loan Abroad',
            cName: 'RIKIMARU',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63565537',
            lan: 'LA-OFW-63565537',
            loanProd: 'OFW - Loan Abroad',
            cName: 'BARATHRUM',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'NEW',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63590533',
            lan: 'LA-OFW-63590533',
            loanProd: 'OFW - Loan Abroad',
            cName: 'THINKER',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'NEW',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63500053',
            lan: 'LA-OFW-63500053',
            loanProd: 'OFW - Loan Abroad',
            cName: 'WARLOCK',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63598773',
            lan: 'LA-OFW-63598773',
            loanProd: 'OFW - Loan Abroad',
            cName: 'TERROR BLADE',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63173465',
            lan: 'LA-OFW-63173465',
            loanProd: 'DH - Loan Abroad',
            cName: 'MAGINA',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
        {
            key: 'LA-OFW-63196411',
            lan: 'LA-OFW-63196411',
            loanProd: 'DH - Loan Abroad',
            cName: 'EARTH SHAKER',
            odd: 'NO DEPARTURE DATE',
            lc: 'Boss Toyo',
            renew: 'RENEWAL',
            lb: 'Ortigas',
            stat: 'FOR SCREENING',
            sb: '',
            lr: '',
            statrem: '03/24/2024 09:45 AM',
            upby: 'Boss Phevos',
            inup: '03/25/2024 11:32 AM',
            doa: '03/23/2024 8:37 AM',
        },
    ]
    return dataList;
}